NodeIP: YOUR.FULLNODE.IP.HERE
NodePort: YOURFULLNODEPORTHERE
NodeUser: YOURFULLNODEUSERNAME
NodePass: YOURFULLNODEPASS
WalletsToMonitor: WalletName1,WalletName2
ServerPort: 11235
SMSNumber: 5558675309
SMSWarnTimeSeconds: 500
